# Generated by Django 5.2.3 on 2025-06-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
