# Generated by Django 5.2.3 on 2025-06-20 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlistuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
